# Generated by Django 5.1.3 on 2024-11-18 08:50

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number format: +84xxxxxxxxx', max_length=128, region='VN'),
        ),
    ]
